### ISSUE TITLE
 java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class 

### ISSUE THREAD

**Issue by Apollo55** [MarkusBauer/helden-software-loader#10]
Hi,
ich bin beim versuch das Plugin zu starten auf eine Fehlermeldung gestoßen. Ist das Projekt noch aktive?

```
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5b2133b1
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:200)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:194)
        at de.mb.heldensoftware.customentries.InstrumentationEngine.patchClass(InstrumentationEngine.java:31)
        at de.mb.heldensoftware.customentries.PluginSideloader.patchHeldenPluginFactory(PluginSideloader.java:35)
        at de.mb.heldensoftware.customentries.PluginSideloader.registerSideloader(PluginSideloader.java:25)
        at de.mb.heldensoftware.customentries.HeldenLauncher.main(HeldenLauncher.java:24)
```
        
Könnte ein Version Problem sein. Momentan habe ich Java 18 Installiert

**Comment by Apollo55** [comment]
Start mit Java 11 ohne Probleme!

**Comment by MarkusBauer** [comment]
Hi, 
Java 16 hat eine Funktion deaktiviert, die das Plugin leider braucht (Reflection gegen den Classloader).
Ich hab eine [neue Version (1.6)](https://github.com/MarkusBauer/helden-software-loader/releases/tag/v1.6) hochgeladen, die das Problem zumindest umgehen sollte. Funktioniert bei mir mit Java 18 problemlos unter Windows und Linux.
